name: Build GUI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
  
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: Source1Import latest (${GITHUB_REF##*/})
        path: dist/windows
